package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Beverage generated by hbm2java
 */
@Entity
@Table(name="beverage"
    ,catalog="web_store"
)
public class Beverage extends ParentEntity implements java.io.Serializable {


     private int beverageId;
     private Product product;
     private String type;
     private int volume;
     private int alcohol;

    public Beverage() {
    }

    public Beverage(Product product, String type, int volume, int alcohol) {
       this.product = product;
       this.type = type;
       this.volume = volume;
       this.alcohol = alcohol;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="product"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="beverage_id", unique=true, nullable=false)
    public int getBeverageId() {
        return this.beverageId;
    }
    
    public void setBeverageId(int beverageId) {
        this.beverageId = beverageId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="volume", nullable=false)
    public int getVolume() {
        return this.volume;
    }
    
    public void setVolume(int volume) {
        this.volume = volume;
    }

    
    @Column(name="alcohol", nullable=false)
    public int getAlcohol() {
        return this.alcohol;
    }
    
    public void setAlcohol(int alcohol) {
        this.alcohol = alcohol;
    }




}


