package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="web_store"
)
public class Customer extends ParentEntity  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private Integer purchases;
     private BigDecimal accountBalance;
     private Set purchases_1 = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String firstName, String lastName, String email, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
    }
    public Customer(String firstName, String lastName, String email, String password, Integer purchases, BigDecimal accountBalance, Set purchases_1) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.purchases = purchases;
       this.accountBalance = accountBalance;
       this.purchases_1 = purchases_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="purchases")
    public Integer getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Integer purchases) {
        this.purchases = purchases;
    }

    
    @Column(name="account_balance")
    public BigDecimal getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(BigDecimal accountBalance) {
        this.accountBalance = accountBalance;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set getPurchases_1() {
        return this.purchases_1;
    }
    
    public void setPurchases_1(Set purchases_1) {
        this.purchases_1 = purchases_1;
    }




}


