package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name="food"
    ,catalog="web_store"
)
public class Food  extends ParentEntity  implements java.io.Serializable {


     private int foodId;
     private Product product;
     private int weight;
     private String type;

    public Food() {
    }

    public Food(Product product, int weight, String type) {
       this.product = product;
       this.weight = weight;
       this.type = type;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="product"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="food_id", unique=true, nullable=false)
    public int getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="weight", nullable=false)
    public int getWeight() {
        return this.weight;
    }
    
    public void setWeight(int weight) {
        this.weight = weight;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


