package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.math.MathContext;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="web_store"
)
public class Product extends ParentEntity implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private BigDecimal price;
     private BigDecimal finalPrice;
     private double discount;
     private int barCode;
     private Integer quantity;
     private String image;
     private String description;
     private String orign;
     private Food food;
     private Set purchases = new HashSet(0);
     private Beverage beverage;

    public Product() {
    }

	
    public Product(String productName, BigDecimal price, int barCode) {
        this.productName = productName;
        this.price = price;
        this.barCode = barCode;
    }
    public Product(String productName, BigDecimal price, double discount, int barCode, Integer quantity, String image, String description, String orign, Food food, Set purchases, Beverage beverage) {
       this.productName = productName;
       this.price = price;
       this.discount=discount;
       this.barCode = barCode;
       this.quantity = quantity;
       this.image = image;
       this.description = description;
       this.orign = orign;
       this.food = food;
       this.purchases = purchases;
       this.beverage = beverage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="price", nullable=false, precision=6)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
    public double getFinalPrice(){
     return  (this.getPrice().subtract(this.getPrice().divide(BigDecimal.valueOf(100)).multiply(BigDecimal.valueOf(this.getDiscount())))).doubleValue();
    }

    
    @Column(name="bar_code", nullable=false)
    public int getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(int barCode) {
        this.barCode = barCode;
    }
    
@Column(name="discount", nullable=false)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount=discount;
    }

    
    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="image", length=45)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="orign", length=45)
    public String getOrign() {
        return this.orign;
    }
    
    public void setOrign(String orign) {
        this.orign = orign;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="product")
    public Food getFood() {
        return this.food;
    }
    
    public void setFood(Food food) {
        this.food = food;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="product")
    public Beverage getBeverage() {
        return this.beverage;
    }
    
    public void setBeverage(Beverage beverage) {
        this.beverage = beverage;
    }




}


