package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="web_store"
)
public class Purchase implements java.io.Serializable {


     private PurchaseId id;
     private Customer customer;
     private Product product;
     private Date timeOfPurchase;

    public Purchase() {
    }

	
    public Purchase(PurchaseId id, Customer customer, Product product) {
        this.id = id;
        this.customer = customer;
        this.product = product;
    }
    public Purchase(PurchaseId id, Customer customer, Product product, Date timeOfPurchase) {
       this.id = id;
       this.customer = customer;
       this.product = product;
       this.timeOfPurchase = timeOfPurchase;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerFk", column=@Column(name="customer_fk", nullable=false) ), 
        @AttributeOverride(name="productFk", column=@Column(name="product_fk", nullable=false) ) } )
    public PurchaseId getId() {
        return this.id;
    }
    
    public void setId(PurchaseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="customer_fk", nullable=false, insertable=false, updatable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="product_fk", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_of_purchase", length=26)
    public Date getTimeOfPurchase() {
        return this.timeOfPurchase;
    }
    
    public void setTimeOfPurchase(Date timeOfPurchase) {
        this.timeOfPurchase = timeOfPurchase;
    }




}


