package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchaseId generated by hbm2java
 */
@Embeddable
public class PurchaseId  implements java.io.Serializable {


     private int customerFk;
     private int productFk;

    public PurchaseId() {
    }

    public PurchaseId(int customerFk, int productFk) {
       this.customerFk = customerFk;
       this.productFk = productFk;
    }
   


    @Column(name="customer_fk", nullable=false)
    public int getCustomerFk() {
        return this.customerFk;
    }
    
    public void setCustomerFk(int customerFk) {
        this.customerFk = customerFk;
    }


    @Column(name="product_fk", nullable=false)
    public int getProductFk() {
        return this.productFk;
    }
    
    public void setProductFk(int productFk) {
        this.productFk = productFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PurchaseId) ) return false;
		 PurchaseId castOther = ( PurchaseId ) other; 
         
		 return (this.getCustomerFk()==castOther.getCustomerFk())
 && (this.getProductFk()==castOther.getProductFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCustomerFk();
         result = 37 * result + this.getProductFk();
         return result;
   }   

   


}


