package model;
// Generated Sep 4, 2019 11:52:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seen generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="web_store"
)
public class Seen implements java.io.Serializable {


     private SeenId id;
     private Customer customer;
     private Product product;
     private Date lastTimeSeen;
     private Date firstTimeSeen;
     private int timesSeen;

    public Seen() {
    }

	
    public Seen(SeenId id, Customer customer, Product product) {
        this.id = id;
        this.customer = customer;
        this.product = product;
    }
    public Seen(SeenId id, Customer customer, Product product, int timesSeen, Date firstTimeSeen, Date lastTimeSeen) {
       this.id = id;
       this.customer = customer;
       this.product = product;
       this.timesSeen = timesSeen;
       this.firstTimeSeen=firstTimeSeen;
       this.lastTimeSeen=lastTimeSeen;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerFk", column=@Column(name="customer_fk", nullable=false) ), 
        @AttributeOverride(name="productFk", column=@Column(name="product_fk", nullable=false) ) } )
    public SeenId getId() {
        return this.id;
    }
    
    public void setId(SeenId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="customer_fk", nullable=false, insertable=false, updatable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="product_fk", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="first_time_seen", length=26)
    public Date getFirstTimeSeen() {
        return this.firstTimeSeen;
    }
    
    public void setFirstTimeSeen(Date firstTimeSeen) {
        this.firstTimeSeen=firstTimeSeen;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_time_seen", length=26)
    public Date getLastTimeSeen() {
        return this.lastTimeSeen;
    }
    
    public void setLastTimeSeen(Date lastTimeSeen) {
        this.lastTimeSeen=lastTimeSeen;
    }
    
     @Column(name="times_seen", nullable=false)
    public int getTimesSeen() {
        return this.timesSeen;
    }
    
    public void setTimesSeen(int timesSeen) {
        this.timesSeen=timesSeen;
    }



}

